version: '3.8'

include:
  - path: .docker/docs.compose.yaml
  - path: .docker/otel.compose.yaml

services:
  postgres-primary:
    image: bitnami/postgresql:latest
    container_name: pg-primary
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1g
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_pass
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: tiny_url
      POSTGRESQL_SHARED_BUFFERS: 128MB
      POSTGRESQL_EFFECTIVE_CACHE_SIZE: 256MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - primary_data:/bitnami/postgresql

  postgres-replica:
    image: bitnami/postgresql:latest
    container_name: pg-replica
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1g
    ports:
      - "5433:5432"
    depends_on:
      - postgres-primary
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_pass
      POSTGRESQL_MASTER_HOST: postgres-primary
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_SHARED_BUFFERS: 128MB
      POSTGRESQL_EFFECTIVE_CACHE_SIZE: 256MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - replica_data:/bitnami/postgresql

  redis:
    image: redis:7-alpine
    container_name: redis
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512m
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    profiles:
      - app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${APP_VERSION:-0.0.1}
    container_name: app
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512m
    image: tiny-url:local
    labels:
      com.datadoghq.ad.logs: >
        [{
          "source": "go",
          "service": "tiny-url"
        }]
    env_file:
      - .envs/local.env
    environment:
      - CACHE_HOST=redis
      - TELEMETRY_HOST=dd-agent
      - DB_HOST=pg-primary
      - DB_REPLICA_HOST=pg-replica
      - DB_REPLICA_PORT=5432
    ports:
      - "8080:8080"
    healthcheck:
          test: ["CMD", "curl", "-fsS", "http://localhost:8080/health/ready"]
          interval: 5s
          timeout: 1s
          retries: 3
    depends_on:
      - redis
      - dd-agent
      - postgres-primary
      - postgres-replica

volumes:
  redis_data:
  primary_data:
  replica_data: